[versions]

agp = "8.13.0"
kotlin = "2.2.21"
koin = "4.1.1"
android-appcompat = "1.7.1"
mockito = "5.2.0"

[libraries]
android-appcompat = {module = "androidx.appcompat:appcompat", version.ref = "android-appcompat"}
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-test = { module = "io.insert-koin:koin-android-test", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
mockito = {module = "org.mockito:mockito-inline", version.ref = "mockito"}

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
