[versions]

agp = "8.13.0"
kotlin = "2.2.21"
koin = "4.1.1"
android-appcompat = "1.7.1"
koin-annotations = "2.3.1"
ksp = "2.3.2"
mockito = "5.2.0"

[libraries]
android-appcompat = {module = "androidx.appcompat:appcompat", version.ref = "android-appcompat"}
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }
mockito = {module = "org.mockito:mockito-inline", version.ref = "mockito"}

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }