[versions]
kotlin = "2.2.21"
ktor = "3.3.2"
koin = "4.1.1"
koin-annotations = "2.3.1"
ksp = "2.3.2"

mockito = "4.8.0"

logback = "1.4.12"

[libraries]
ktor-server = {module = "io.ktor:ktor-server-netty", version.ref = "ktor"}
ktor-test = {module = "io.ktor:ktor-server-test-host", version.ref = "ktor"}
logback = {module = "ch.qos.logback:logback-classic", version.ref = "logback"}
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-ktor-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }

koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-jsr330 = { module = "io.insert-koin:koin-jsr330", version.ref = "koin-annotations" }
koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }

mockito = {module = "org.mockito:mockito-inline", version.ref = "mockito"}


[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = {id = "com.google.devtools.ksp", version.ref = "ksp"}